App_Blog/urls.py

from django.urls import path 
from . import views


app_name = 'App_Blog'


urlpatterns = [
        path('',views.BlogList.as_view(), name='blog_list'),
        path('write/',views.CreateBlog.as_view(),name='create_blog'),
        path('details/<slug:slug>/',views.blog_details,name='blog_details'),  
        path('liked/<pk>/',views.liked,name='liked_post'),
        path('unliked/<pk>/',views.unliked,name='unliked_post'),
        path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
        path('edit_blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),

]

App_Login/urls.py

from django.urls import path 
from . import views


app_name = 'App_Login'
urlpatterns = [
    

    path('signup',views.sign_up,name='signup'),
    path('signin',views.login_page,name='signin'),
    path('logout',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change-profile/',views.user_change,name='user_change'),
    path('password/',views.pass_change,name='pass_change'),
    path('change-profile-image/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('contact/',views.contact_me,name='contact'),
]

Blog/urls.py


from django.contrib import admin
from django.urls import path ,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('',views.index ,name='index')

]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User ,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')





class Contact(models.Model):

    name = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField(max_length=256)



    def __str__(self):
        return self.name + ' has messaged you!' 


    
    

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm 
from django.contrib.auth.models import User
from .models import UserProfile,Contact
class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address",required=True)
    class Meta:
       model = User
       fields = ('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')




class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =  ['profile_pic']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login,authenticate,logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm,UserProfileChange ,ProfilePic,ContactForm
from django.contrib import messages
# Create your views here.

def sign_up(request):

    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    dict = {'form':form,   'registered':registered}
    return render(request,'App_Login/signup.html',context=dict)

    
def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            
    return render(request, 'App_Login/login.html',context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))

@login_required
def profile(request):
    return render(request, 'App_Login/profile.html',context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html',context={'form':form})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request,'App_Login/pass_change.html',context={'form':form,'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html',context={'form':form})


@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method =='POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile) #arg2 ==>i added encytype in the template button
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html',context={'form':form})






def contact_me(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your message was sent successfully!')
            return HttpResponseRedirect(reverse('App_Login:contact'))
    else:
        form = ContactForm()

    return render(request, 'App_Login/contact.html', context={'form': form})



templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% block title %} Edit Profile{% endblock  %}


{% block body_block %}
<h2> Profile Edit:</h2>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary btn-sm">Edit</button>
</form>
     <a href="{% url 'App_Login:pass_change' %}" class="badge bg-primary">Clic here if you want to change your password</a> *

{% endblock body_block %}

templates/App_Login/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Contact Me</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-dark" id="mainNav">
            <div class="container px-4 px-lg-5">
              <a class="navbar-brand" href="{% url 'index' %}" id="homeLink">Home</a>
          
              <!-- Add a toggle button for mobile -->
              <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>Menu
              </button>
          
              <!-- Add the navigation links inside a collapsible div -->
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                  {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:logout' %}"><i class="bi bi-box-arrow-in-left"></i>Logout</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Blog:create_blog' %}">Post a Blog<i class="bi bi-pencil-square"></i></a></li>
                  {% else %}
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:signup' %}">Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:signin' %}">Login<i class="bi bi-box-arrow-in-right"></i></a></li>
                  {% endif %}
                  <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:contact' %}">Contact Me <i class="bi bi-envelope-plus-fill"></i></a></li>
                  {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a href="#" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
                        <i class="bi bi-gear"></i> {{ user.username }}
                      </a>
                      <div class="dropdown-menu">
                        <a href="{% url 'App_Blog:my_blogs' %}" class="dropdown-item"><i class="bi bi-file-text-fill"></i> My Blog</a>
                        <a href="{% url 'App_Login:profile' %}" class="dropdown-item"><i class="bi bi-person-circle"></i> Your Profile</a>
                        <a href="{% url 'App_Login:logout' %}" class="dropdown-item"><i class="bi bi-box-arrow-in-left"></i> Logout</a>
                      </div>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
          
          <script>
            
              // Function to toggle the mobile menu
              function toggleMobileMenu() {
                const navbarCollapse = document.getElementById('navbarResponsive');
                if (navbarCollapse.classList.contains('show')) {
                  navbarCollapse.classList.remove('show');
                } else {
                  navbarCollapse.classList.add('show');
                }
              }
            
              // Add a click event listener to the menu button
              const menuButton = document.querySelector('.navbar-toggler');
              menuButton.addEventListener('click', toggleMobileMenu);
            
            </script>
            <style>
      
              #homeLink {
                color: #fff; 
              }
      
              /* Add this CSS to your stylesheet to style the navigation menu */
              #navbarResponsive {
                background-color: #212529; /* Change this to your desired background color */
              }
            
              #navbarResponsive a.nav-link {
                color: #DCD2D0; /* Change this to your desired text color */
              }
            
              /* Add any additional CSS styles you need */
            </style>
      













        <!-- Page Header-->
        <header class="masthead" style="background-image: url('/media/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                           
                            
                            <form id="contactForm" action="{% url 'App_Login:contact' %}" method="post" class="mt-5">
                                {% csrf_token %}
                            
                                <!-- Name Field -->
                                <div class="form-group">
                                    <label for="{{ form.name.id_for_label }}">Name</label>
                                    {{ form.name }}
                                </div>
                            
                                <!-- Email Field -->
                                <div class="form-group">
                                    <label for="{{ form.email.id_for_label }}">Email</label>
                                    {{ form.email }}
                                </div>
                            
                                <!-- Phone Field -->
                                <div class="form-group">
                                    <label for="{{ form.phone.id_for_label }}">Phone</label>
                                    {{ form.phone }}
                                </div>
                            
                                <!-- Message Field -->
                                <div class="form-group">
                                    <label for="{{ form.message.id_for_label }}">Message</label>
                                    {{ form.message }}
                                </div>
                            
                                <!-- Submit Button -->
                                <button class="btn btn-primary" type="submit">Send</button>
                            </form>

                            {% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}


                            <!-- Modal for Success Message -->


                            
                            <!-- Custom CSS for form styling -->
                            <style>
                                /* Form container style */
                                #contactForm {
                                    max-width: 400px;
                                    margin: 0 auto;
                                }
                            
                                /* Form input style */
                                .form-group {
                                    margin-bottom: 20px;
                                }
                            
                                label {
                                    font-weight: bold;
                                }
                            
                                input[type="text"],
                                input[type="email"],
                                textarea {
                                    width: 100%;
                                    padding: 10px;
                                    border: 1px solid #ccc;
                                    border-radius: 5px;
                                }
                            
                               
                            </style>
                            
                            

                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="text-center text-white" style="background-color: #f1f1f1;">
            <!-- Grid container -->
            <div class="container pt-4">
              <!-- Section: Social media -->
              <section class="mb-4">
                <!-- Facebook -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="https://www.facebook.com/people/IL-Yas/pfbid0BiJNPTtpnbcVAQjkLMRWbArqNWqAZHNAicZfXqWMADbQXJZJ69vbMzkrDD4qZjjSl/"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-facebook-f"></i
                ></a>
          
                <!-- Twitter -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="https://twitter.com/i_iliees"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-twitter"></i
                ></a>
          
                <!-- Google -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-google"></i
                ></a>
          
                <!-- Instagram -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="https://www.instagram.com/i_iliees_/?hl=af"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-instagram"></i
                ></a>
          
                <!-- Linkedin -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="https://www.linkedin.com/in/ilies-bouchouareb-80a18a218/"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-linkedin"></i
                ></a>
                <!-- Github -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="https://github.com/iliees"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-github"></i
                ></a>
              </section>
              <!-- Section: Social media -->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
              © 2023 Copyright:
              <a class="text-dark" href="https://mdbootstrap.com/">ilies BOUCHOUAREB</a>
              <br>
              Email <i class="bi bi-envelope-at-fill"></i>: bouchouarebilies@gmail.com
            </div>
            <!-- Copyright -->
          </footer>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static "js/scripts.js" %}"></script>
    
    </body>
</html>

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login Page{% endblock  %}


{% block body_block %}
<h2> Login to you Account</h2>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary btn-sm">Login</button>
</form>

{% endblock body_block %}

templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% block title %} Change your Password{% endblock  %}


{% block body_block %}

{% if changed %}

<div class="alert alert-success">
    Password changed Successfully
</div>
{% endif %}
<h2> Changer Your Password</h2>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary btn-sm">change</button>
</form>

{% endblock body_block %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% block title %}Profile Picture update{% endblock  %}


{% block body_block %}
<h2>add your Profile Picture</h2>
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    
    <button type="submit" class="btn btn-primary btn-sm">Add Picture</button>
</form>

{% endblock body_block %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title %} Profile Page{% endblock  %}


{% block body_block %}

<h2>Your Profile</h2>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px">
<br><br>
<a href="{% url "App_Login:change_pro_pic" %}" class="btn btn-info btn-sm">Change Profile Picture</a>


{% else %}
<img src="/media/defaultimage.jpeg" class="rounded-circle" width="120px">
<br>
<a href="{% url "App_Login:add_pro_pic" %}" class="btn btn-info btn-sm">Change Profile Picture</a>

{% endif %}



<p>Username : {{ user.username }}</p>
<p>Email : {{ user.email }}</p>
<p>Name : {{ user.first_name }} {{ user.last_name}} </p>

<br>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Infos</a>
{% endblock  %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create New Account{% endblock  %}


{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    Account Created Successfully <a href="{% url 'App_Login:signin' %}">Login Here</a>
</div>
{% else %}
<h2> Create New Account</h2>
<form method="post">

{{ form.as_p  }}

{% csrf_token %}

<button type="submit" class="btn btn-success btn-sm"> Create Account</button>

</form>
<br>
<p>Already have an account ? <a href="{% url 'App_Login:signin' %}">Login Here</a></p>
{% endif %}


{% endblock body_block %}