App_Blog/urls.py

from django.urls import path 
from . import views


app_name = 'App_Blog'


urlpatterns = [
        path('',views.BlogList.as_view(), name='blog_list'),
        path('write/',views.CreateBlog.as_view(),name='create_blog'),
        path('details/<slug:slug>/',views.blog_details,name='blog_details'),  
        path('liked/<pk>/',views.liked,name='liked_post'),
        path('unliked/<pk>/',views.unliked,name='unliked_post'),
        path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
        path('edit_blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),

]

App_Login/urls.py

from django.urls import path 
from . import views


app_name = 'App_Login'
urlpatterns = [
    

    path('signup',views.sign_up,name='signup'),
    path('signin',views.login_page,name='signin'),
    path('logout',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change-profile/',views.user_change,name='user_change'),
    path('password/',views.pass_change,name='pass_change'),
    path('change-profile-image/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('contact/',views.contact_me,name='contact'),
]

Blog/urls.py


from django.contrib import admin
from django.urls import path ,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('',views.index ,name='index')

]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


templates/base.html
<!doctype html>
<html lang="en">


{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Blogs Page
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body style="background-color: #d7d7d7;">


    <!-- Navigation-->

    <nav class="navbar navbar-expand-lg navbar-light bg-dark" id="mainNav">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'index' %}" id="homeLink">Home</a>
    
        <!-- Add a toggle button for mobile -->
        <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>Menu
        </button>
    
        <!-- Add the navigation links inside a collapsible div -->
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:logout' %}"><i class="bi bi-box-arrow-in-left"></i>Logout</a></li>
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Blog:create_blog' %}">Post a Blog<i class="bi bi-pencil-square"></i></a></li>
            {% else %}
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:signup' %}">Sign Up</a></li>
              <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:signin' %}">Login<i class="bi bi-box-arrow-in-right"></i></a></li>
            {% endif %}
            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'App_Login:contact' %}">Contact Me <i class="bi bi-envelope-plus-fill"></i></a></li>
            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
                  <i class="bi bi-gear"></i> {{ user.username }}
                </a>
                <div class="dropdown-menu">
                  <a href="{% url 'App_Blog:my_blogs' %}" class="dropdown-item"><i class="bi bi-file-text-fill"></i> My Blog</a>
                  <a href="{% url 'App_Login:profile' %}" class="dropdown-item"><i class="bi bi-person-circle"></i> Your Profile</a>
                  <a href="{% url 'App_Login:logout' %}" class="dropdown-item"><i class="bi bi-box-arrow-in-left"></i> Logout</a>
                </div>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    <script>
      
        // Function to toggle the mobile menu
        function toggleMobileMenu() {
          const navbarCollapse = document.getElementById('navbarResponsive');
          if (navbarCollapse.classList.contains('show')) {
            navbarCollapse.classList.remove('show');
          } else {
            navbarCollapse.classList.add('show');
          }
        }
      
        // Add a click event listener to the menu button
        const menuButton = document.querySelector('.navbar-toggler');
        menuButton.addEventListener('click', toggleMobileMenu);
      
      </script>
      <style>

        #homeLink {
          color: #fff; 
        }

        /* Add this CSS to your stylesheet to style the navigation menu */
        #navbarResponsive {
          background-color: #212529; /* Change this to your desired background color */
        }
      
        #navbarResponsive a.nav-link {
          color: #DCD2D0; /* Change this to your desired text color */
        }
      
        /* Add any additional CSS styles you need */
      </style>

    


  
    

    <br><br><br>
   <section class="container"  >


    {% block body_block %}
    
    
    {% endblock  %}
  </section>
    
    
    <footer class="text-center text-white" style="background-color: #f1f1f1;">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.facebook.com/people/IL-Yas/pfbid0BiJNPTtpnbcVAQjkLMRWbArqNWqAZHNAicZfXqWMADbQXJZJ69vbMzkrDD4qZjjSl/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-facebook-f"></i
          ></a>
    
          <!-- Twitter -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://twitter.com/i_iliees"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-twitter"></i
          ></a>
    
          <!-- Google -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-google"></i
          ></a>
    
          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.instagram.com/i_iliees_/?hl=af"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-instagram"></i
          ></a>
    
          <!-- Linkedin -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://www.linkedin.com/in/ilies-bouchouareb-80a18a218/"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-linkedin"></i
          ></a>
          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-dark m-1"
            href="https://github.com/iliees"
            role="button"
            data-mdb-ripple-color="dark"
            ><i class="fab fa-github"></i
          ></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2023 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">ilies BOUCHOUAREB</a>
        <br>
        Email <i class="bi bi-envelope-at-fill"></i>: bouchouarebilies@gmail.com
      </div>
      <!-- Copyright -->
    </footer>


    


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>


  </body>
</html>