App_Blog/urls.py

from django.urls import path 
from . import views


app_name = 'App_Blog'


urlpatterns = [
        path('',views.BlogList.as_view(), name='blog_list'),
        path('write/',views.CreateBlog.as_view(),name='create_blog'),
        path('details/<slug:slug>/',views.blog_details,name='blog_details'),  
        path('liked/<pk>/',views.liked,name='liked_post'),
        path('unliked/<pk>/',views.unliked,name='unliked_post'),
        path('my-blog/',views.MyBlogs.as_view(),name='my_blogs'),
        path('edit_blog/<pk>/',views.UpdateBlog.as_view(),name='edit_blog'),

]

App_Login/urls.py

from django.urls import path 
from . import views


app_name = 'App_Login'
urlpatterns = [
    

    path('signup',views.sign_up,name='signup'),
    path('signin',views.login_page,name='signin'),
    path('logout',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change-profile/',views.user_change,name='user_change'),
    path('password/',views.pass_change,name='pass_change'),
    path('change-profile-image/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('contact/',views.contact_me,name='contact'),
]

Blog/urls.py


from django.contrib import admin
from django.urls import path ,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('',views.index ,name='index')

]

urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):

    author = models.ForeignKey(User ,on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264,verbose_name='Put a title')
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name='what is on you mind ?')
    blog_image = models.ImageField(upload_to='blog_images',verbose_name='Blog Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date']


    def __str__(self):
        return self.blog_title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog ,on_delete=models.CASCADE,related_name='blog_comment')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']

        
    def __str__(self):
        return str(self.user)+' has commented : ' + self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog ,on_delete=models.CASCADE,related_name='liked_blog')
    user = models.ForeignKey(User ,on_delete=models.CASCADE,related_name='liker_user')        

App_Blog/forms.py
from django import forms 
from .models import Blog ,Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Blog/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic import CreateView,UpdateView,ListView,DetailView,TemplateView,DeleteView
from .models import *
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import CommentForm
from slugify import slugify
# Create your views here.


class MyBlogs(LoginRequiredMixin,TemplateView):
    template_name='App_Blog/my_blogs.html'



class UpdateBlog(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ('blog_title','blog_content','blog_image')
    template_name = 'App_Blog/edit_blog.html'

    def get_success_url(self,**kwargs):
        return reverse_lazy('App_Blog:blog_details',kwargs={'slug':self.object.slug})
       


class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'
    queryset = Blog.objects.order_by('publish_date')


class CreateBlog(LoginRequiredMixin,CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title','blog_content','blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        # Generate a slug using slugify
        slug = slugify(title)
        # Check for any existing slugs with the same value
        existing_slugs = Blog.objects.filter(slug__startswith=slug)
        if existing_slugs.count() > 0:
            slug = f"{slug}-{existing_slugs.count() + 1}"  # Append a number to make it unique
        blog_obj.slug = slug
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))
    
         


def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form =CommentForm()
    already_liked = Likes.objects.filter(blog=blog,user=request.user)
    if already_liked:
        liked=True
    else:
        liked=False

    if request.method =='POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'App_Blog/blog_details.html',context={'blog':blog,'comment_form':comment_form,'liked':liked})


@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
        return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))
    

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug})) 

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% block title %} BLOG Details{% endblock  %}


{% block body_block %}





<!-- Page Header-->
<header class="masthead" style="background-image: url('/media/{{blog.blog_image}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{ blog.blog_title }}</h1>
                    <h2 class="subheading"></h2>
                    <span class="meta">
                        Posted by : 
                        <a href="#!"><strong>@{{ blog.author }}</a>
                        on {{ blog.publish_date }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<h6>{{ blog.liked_blog.count }} Likes<i class="bi bi-hand-thumbs-up-fill" id="like-dislike" ></i> | {{ blog.blog_comment.count }} Comments</h6>

<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>
                    {{ blog.blog_content|linebreaks }}
                </p>
            </div>
        </div>
    </div>
</article>











        <hr>
        <style>
            #like-dislike{
        font-size:xxx-large;
            }
        </style> 
        {% if not liked %}
          
        
        <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
            
            <i class="bi bi-hand-thumbs-up" id="like-dislike"></i>
            Hit the Like button if you like this post!
            
        </a>
        {% else %}
        <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
            
            <i class="bi bi-hand-thumbs-up-fill" id="like-dislike" title="Dislike ?"></i>
            You Liked this post!
            
        </a>
        {% endif %}
        <hr>
        <br><br>

        <div class="col-sm-6">
            <form method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                
      
                <button type="submit" class="btn btn-primary btn-sm">Comment</button>
                <button type="button" class="btn btn-outline-primary btn-sm">Cancel</button>
            </form>
        </div>

        <br>

        <h4 class="mb-0">Recent comments:</h4>
                                
        <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>

        <section style="background-color: #4d4341;">

            {% for comment in blog.blog_comment.all %}
            
            <div class="container my-5 py-5">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-12 col-lg-10">
                        <div class="card text-dark">
                            <div class="card-body p-4">
                                
                                

                                     
                                    <div class="d-flex flex-start">
                                        <img class="rounded-circle shadow-1-strong me-3"
                                         src="/media/defaultimage.jpeg" alt="avatar" width="60"
                                         height="60" />
                                            <div>   
                                                
                                                <h6 class="fw-bold mb-1">@{{ comment.user }}</h6>
                                                    <div class="d-flex align-items-center mb-3">
                                                         <p class="mb-0">
                                                              {{ comment.comment_date }}
                                                                <span class="badge bg-primary">Active</span>
                                                         </p>
                                                         
                                                    </div>
                                                    <p class="mb-0">
                                                        {{comment.comment}}
                                                    </p>
                                                    <hr class="my-0" />
                                                    
                                            </div>
                                    </div>
                                       
                            </div>
          
                            
                            
                                
                    
                        </div>
          
                    
          
                    
                    
                    
                    </div>
                </div>
            </div>
            {% endfor %}
        </section>


        






        
           
        </div>

<br><br><br>

    

{% endblock body_block %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load static %}
{% block title %} Home{% endblock  %}









{% block body_block %}



<!-- Page Header-->
<header class="masthead " style="background-image: url('/media/home-bg.jpg')">

     <div class="container position-relative px-4 px-lg-5">
         <div class="row gx-4 gx-lg-5 justify-content-center">
             <div class="col-md-10 col-lg-8 col-xl-7">
                 <div class="site-heading">
                     <h1 class="Chronicles">Wanderlust Chronicles</h1>
                     <span class="subheading">Embark on a virtual journey through the world's most captivating destinations, one story at a time</span>
                 </div>
             </div>
         </div>
     </div>
   </header>




        {% for blog in blogs %}

        <h2>{{ blog.blog_title }}</h2>
        <h6><i>{{ blog.publish_date }}</i></h6>

        <div class="row">
           <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%">
           </div>

           <div class="col-sm-8">
                <p>{{ blog.blog_content|range_filter|linebreaks }}
                    {% if user.is_authenticated %} 
                    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
                    {% else %}
                    <div class="alert alert-warning" role="alert">
                       <a href="{% url 'App_Login:signin' %}">Login to read More!</a> 
                      </div>
                    {% endif %} 
                </p>
                <hr>
                <h6>Posted By: <a href="#">{{ blog.author }}</a></h6>
                <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
           </div>
            <hr>

        </div>







        {% endfor %}



{% endblock body_block %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Create Blog{% endblock  %}


{% block body_block %}

<h2>Write Your Blog Here:</h2>
<form method="post" enctype="multipart/form-data">
    {{form.as_p}}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-sm">Publish</button>
</form>
<br><br><br>

{% endblock body_block %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% block title %} Edit Blog{% endblock  %}


{% block body_block %}

    {% if blog.author == user %}

        <form method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-sm" >Update</button>
        </form>
        {{ else }}
        <p> You are not allowed to edit the post</p>
  
    {% endif %}

{% endblock body_block %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} My Blog{% endblock  %}


{% block body_block %}

    {% for blog in user.post_author.all  %}

        <h3>{{ blog.blog_title }}</h3>
        <h6>{{ blog.publish_date }}</h6>

        <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" alt="" width="100%">
            </div>

            <div class="col-sm-8">
                <p>{{ blog.blog_content|range_filter|linebreaks }}
                    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>      
                  </p>
                  <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>

            </div>
        </div>
        <hr>
        <a href="{% url 'App_Blog:edit_blog' pk=blog.pk %} " class="btn btn-info btn-sm">Edit</a>
        <hr>

    {% endfor %}


{% endblock body_block %}